(function () {
  "use strict";

  window.SolgrandePeopleData = [
    {
      id: "ruben-haldan",
      name: "リューベン・ハルダン",
      englishName: "Ruben Haldan",
      age: 65,
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "村長兼鍛冶屋",
      attribute: "",
      epithet: "",
      specialty: "仲裁・人心掌握",
      appearanceOrder: 7,
      image: "../assets/people/portrait-ruben-haldan.png",
      detailUrl: "entries/ruben-haldan.html"
    },
    {
      id: "celine-haldan",
      name: "セリーヌ・ハルダン",
      englishName: "Céline Haldan",
      age: 58,
      gender: "女性",
      race: "人族",
      origin: "ドルガフ",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "薬師・診療所の運営者",
      attribute: "",
      epithet: "",
      specialty: "薬草調合・治療術",
      appearanceOrder: 8,
      image: "../assets/people/portrait-celine-haldan.png",
      detailUrl: "entries/celine-haldan.html"
    },
    {
      id: "hiram-grun",
      name: "ハイラム・グリュン",
      englishName: "Hiram Grün",
      age: "",
      gender: "男性",
      race: "人族",
      origin: "シネスタディア王国・首都ウルクイ",
      residence: "各地を放浪",
      nation: "シネスタディア王国",
      affiliation: "なし",
      occupation: "錬金術師",
      attribute: "",
      epithet: "",
      specialty: "薬草識別・薬学・錬金術",
      appearanceOrder: 9,
      image: "../assets/people/portrait-hiram-grun.png",
      detailUrl: "entries/hiram-grun.html"
    },
    {
      id: "sallis-lioncourt",
      name: "サリス・リオンコート",
      englishName: "Sallis Lioncourt",
      age: 21,
      gender: "女性",
      race: "人族",
      origin: "シネスタディア王国・フーレイ",
      residence: "フィンリッジ村",
      nation: "シネスタディア王国",
      affiliation: "クローネ家 / リオンコート家",
      occupation: "主婦",
      attribute: "",
      epithet: "",
      specialty: "生活魔法・初級回復魔法・薬草茶",
      appearanceOrder: 10,
      image: "../assets/people/portrait-sallis-lioncourt.png",
      detailUrl: "entries/sallis-lioncourt.html"
    },
    {
      id: "cassian-hales",
      name: "カシアン・ヘイルズ",
      englishName: "Cassian Hales",
      age: 38,
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "フィンリッジ村の教会",
      occupation: "司祭",
      attribute: "",
      epithet: "",
      specialty: "初級回復魔法・解毒魔法・薬学・浄化魔法",
      appearanceOrder: 11,
      image: "../assets/people/portrait-cassian-hales.png",
      detailUrl: "entries/cassian-hales.html"
    },
    {
      id: "rin-seriol",
      name: "リン・セリオール",
      englishName: "Rin Seriol",
      age: 20,
      gender: "女性",
      race: "人族",
      origin: "タレンフォール要塞公国・チップトン",
      residence: "タレンフォール要塞公国・首都シャールカタフ",
      nation: "タレンフォール要塞公国",
      affiliation: "首都シャールカタフの冒険者ギルド本部",
      occupation: "Bランク冒険者",
      attribute: "",
      epithet: "",
      specialty: "氷旋流剣術・リュートの弾き語り",
      appearanceOrder: 12,
      image: "../assets/people/portrait-rin-seriol.png",
      detailUrl: "entries/rin-seriol.html"
    }
  ];
})();
