(function () {
  "use strict";

  window.SolgrandePeopleData = [
    {
      id: "ruben-haldan",
      name: "リューベン・ハルダン",
      englishName: "Ruben Haldan",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "村長・鍛冶師",
      attribute: "",
      epithet: "",
      specialty: "仲裁・人心掌握",
      appearanceOrder: 7,
      image: "../assets/people/portrait-ruben-haldan.png",
      pending: true,
      detailUrl: "entries/ruben-haldan.html"
    },
    {
      id: "celine-haldan",
      name: "セリーヌ・ハルダン",
      englishName: "Céline Haldan",
      gender: "女性",
      race: "人族",
      origin: "ドルガフ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "主婦・錬金術師・薬師",
      attribute: "",
      epithet: "",
      specialty: "薬草調合・治療術",
      appearanceOrder: 8,
      image: "../assets/people/portrait-celine-haldan.png",
      detailUrl: "entries/celine-haldan.html"
    },
    {
      id: "hiram-grun",
      name: "ハイラム・グリュン",
      englishName: "Hiram Grün",
      gender: "男性",
      race: "人族",
      origin: "ウルクイ",
      residence: "各地を放浪した後、後のフィンリッジ村となる集落に定住",
      nation: "シネスタディア王国",
      affiliation: "無所属",
      occupation: "錬金術師・薬師",
      attribute: "",
      epithet: "",
      specialty: "薬草識別・薬学・錬金術",
      appearanceOrder: 9,
      image: "../assets/people/portrait-hiram-grun.png",
      pending: true,
      detailUrl: "entries/hiram-grun.html"
    },
    {
      id: "sallis-lioncourt",
      name: "サリス・リオンコート",
      englishName: "Sallis Lioncourt",
      gender: "女性",
      race: "人族",
      origin: "シネスタディア王国・フーレイ",
      residence: "フィンリッジ村",
      nation: "シネスタディア王国",
      affiliation: "クローネ家 / リオンコート家",
      occupation: "主婦",
      attribute: "",
      epithet: "",
      specialty: "生活魔法・初級回復魔法・薬草茶",
      appearanceOrder: 10,
      image: "../assets/people/portrait-sallis-lioncourt.png",
      detailUrl: "entries/sallis-lioncourt.html"
    },
    {
      id: "cassian-hales",
      name: "カシアン・ヘイルズ",
      englishName: "Cassian Hales",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "司祭",
      attribute: "",
      epithet: "",
      specialty: "初級回復魔法・解毒魔法・薬学・浄化魔法",
      appearanceOrder: 11,
      image: "../assets/people/portrait-cassian-hales.png",
      pending: true,
      detailUrl: "entries/cassian-hales.html"
    },
    {
      id: "rin-seriol",
      name: "リン・セリオール",
      englishName: "Rin Seriol",
      gender: "女性",
      race: "人族",
      origin: "タレンフォール要塞公国・チップトン",
      residence: "タレンフォール要塞公国・首都シャールカタフ",
      nation: "タレンフォール要塞公国",
      affiliation: "首都シャールカタフの冒険者ギルド本部",
      occupation: "Bランク冒険者",
      attribute: "",
      epithet: "",
      specialty: "氷旋流剣術・リュートの弾き語り",
      appearanceOrder: 12,
      image: "../assets/people/portrait-rin-seriol.png",
      pending: true,
      detailUrl: "entries/rin-seriol.html"
    },
    {
      id: "mord-barski",
      name: "モルド・バースキー",
      englishName: "Mord Barski",
      gender: "男性",
      race: "人族",
      origin: "エイジェルトン",
      residence: "ツァダル",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "店主",
      attribute: "",
      epithet: "",
      specialty: "創作料理・利き酒",
      appearanceOrder: 13,
      image: "../assets/people/portrait-mord-barski.png",
      pending: true,
      detailUrl: "entries/mord-barski.html"
    },
    {
      id: "kieval-lioncourt",
      name: "キーヴァル・リオンコート",
      englishName: "Kieval Lioncourt",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国 / 自警団",
      occupation: "自警団員",
      attribute: "",
      epithet: "",
      specialty: "剣術・体術",
      appearanceOrder: 14,
      image: "../assets/people/portrait-kieval-lioncourt.png",
      detailUrl: "entries/kieval-lioncourt.html"
    },
    {
      id: "arvhel-lioncourt",
      name: "アーヴェル・リオンコート",
      englishName: "Arvhel Lioncourt",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "冒険者",
      attribute: "",
      epithet: "",
      specialty: "料理・アクセサリー作り・動物やモンスターの扱い",
      appearanceOrder: 15,
      image: "../assets/people/portrait-arvhel-lioncourt.png",
      detailUrl: "entries/arvhel-lioncourt.html"
    },
    {
      id: "tora-harland",
      name: "トーラ・ハーランド",
      englishName: "Tora Harland",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "",
      attribute: "",
      epithet: "",
      specialty: "釣り・先の先・後の先",
      appearanceOrder: 16,
      image: "../assets/people/portrait-tora-harland.png",
      detailUrl: "entries/tora-harland.html"
    },
    {
      id: "milica-lioncourt",
      name: "ミリカ・リオンコート",
      englishName: "Milica Lioncourt",
      gender: "女性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "",
      attribute: "",
      epithet: "",
      specialty: "木登り・家事・剣術",
      appearanceOrder: 17,
      image: "../assets/people/portrait-milica-lioncourt.png",
      detailUrl: "entries/milica-lioncourt.html"
    },
    {
      id: "barks-harland",
      name: "バークス・ハーランド",
      englishName: "Barks Harland",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "フィンリッジ村自警団団長",
      attribute: "",
      epithet: "",
      specialty: "利き酒・釣り・弓術・索敵・偵察・追跡・野外活動",
      appearanceOrder: 18,
      image: "../assets/people/portrait-barks-harland.png",
      detailUrl: "entries/barks-harland.html"
    },
    {
      id: "darius-haldan",
      name: "ダリウス・ハルダン",
      englishName: "Darius Haldan",
      gender: "男性",
      race: "人族",
      origin: "フィンリッジ",
      residence: "フィンリッジ",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "雑貨店店主",
      attribute: "",
      epithet: "",
      specialty: "値段交渉・身体強化・鑑定",
      appearanceOrder: 19,
      image: "../assets/people/portrait-darius-haldan.png",
      pending: true,
      detailUrl: "entries/darius-haldan.html"
    },
    {
      id: "rokel-kolpor",
      name: "ロケル・コルポール",
      englishName: "Rokel Kolpor",
      gender: "男性",
      race: "人族",
      origin: "ウグ＝ネル",
      residence: "ウグ＝ネル",
      nation: "ベルモーシア",
      affiliation: "ベルモーシア",
      occupation: "雑貨店店主",
      attribute: "",
      epithet: "",
      specialty: "暗算・先見性",
      appearanceOrder: 20,
      image: "../assets/people/portrait-rokel-kolpor.png",
      detailUrl: "entries/rokel-kolpor.html"
    },
    {
      id: "komel-kolpor",
      name: "コメル・コルポール",
      englishName: "Komel Kolpor",
      gender: "男性",
      race: "人族",
      origin: "ウグ＝ネル",
      residence: "ウグ＝ネル",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "",
      attribute: "",
      epithet: "",
      specialty: "釣り・読み書き・計算",
      appearanceOrder: 21,
      image: "../assets/people/portrait-komel-kolpor.png",
      detailUrl: "entries/komel-kolpor.html"
    },
    {
      id: "marta-brown",
      name: "マルタ・ブラウン",
      englishName: "Marta Brown",
      gender: "女性",
      race: "人族",
      origin: "フィンリッジ村",
      residence: "フィンリッジ村",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "ハースルート女将",
      attribute: "",
      epithet: "",
      specialty: "人の顔と名前を覚えること・料理",
      appearanceOrder: 22,
      image: "../assets/people/portrait-marta-brown.png",
      pending: true,
      detailUrl: "entries/marta-brown.html"
    },
    {
      id: "pedra",
      name: "ペドラ",
      englishName: "Pedra",
      gender: "女性",
      race: "獣人 コヨーテ種",
      origin: "不明",
      residence: "不定",
      nation: "ベルモーシア公国",
      affiliation: "ベルモーシア公国",
      occupation: "Eランク冒険者",
      attribute: "",
      epithet: "",
      specialty: "サバイバル術・優れた聴覚・優れた嗅覚・高い瞬発力・我流の戦闘術",
      appearanceOrder: 23,
      image: "../assets/people/portrait-pedra.png",
      detailUrl: "entries/pedra.html"
    }
  ];
})();
